'use client';
import {useCallback,useEffect,useState} from 'react';

type AnyData=Record<string,any>;
const phaseName:Record<string,string>={lobby:'대기실',negotiation:'협상',secret:'비밀 행동',result:'결과 확인',guess:'최종 추리',finished:'종료'};
const phaseHelp:Record<string,string>={lobby:'6명이 모두 들어오면 교사가 시작합니다.',negotiation:'말로 협상하세요. 지금은 앱에서 행동하지 않습니다.',secret:'에너지 전환 1회 + 익명 전달 1회가 가능합니다.',result:'전달 결과와 완성된 경로를 확인하세요.',guess:'다른 플레이어 1명의 역할을 추리하세요.',finished:'모든 역할과 최종 점수가 공개되었습니다.'};
async function api(body:AnyData):Promise<any>{const r=await fetch('/api/game',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d}
function Timer({deadline}:{deadline:number|null}){const [now,setNow]=useState(Date.now());useEffect(()=>{const i=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(i)},[]);if(!deadline)return null;const s=Math.max(0,Math.ceil((deadline-now)/1000));return <span className="timer">{String(Math.floor(s/60)).padStart(2,'0')}:{String(s%60).padStart(2,'0')}</span>}

export default function Home(){
 const [mode,setMode]=useState<'home'|'student'|'teacher'>('home'); const [data,setData]=useState<AnyData|null>(null); const [auth,setAuth]=useState<AnyData>({}); const [error,setError]=useState('');
 useEffect(()=>{try{const saved=sessionStorage.getItem('solar-journey-auth');if(saved){const a=JSON.parse(saved);setAuth(a);setMode(a.teacherToken?'teacher':'student')}}catch{}},[]);
 useEffect(()=>{if(auth.code)sessionStorage.setItem('solar-journey-auth',JSON.stringify(auth));},[auth]);
 const refresh=useCallback(async()=>{if(!auth.code)return;try{setData(await api(auth.teacherToken?{action:'getTeacher',sessionCode:auth.code,teacherToken:auth.teacherToken}:{action:'get',code:auth.code,playerToken:auth.playerToken}))}catch{}},[auth]);
 useEffect(()=>{if(!auth.code)return;const i=setInterval(refresh,2500);return()=>clearInterval(i)},[auth,refresh]);
 async function run(body:AnyData):Promise<any>{setError('');try{const d:any=await api(body);setData(d.kind?d:null);return d}catch(e){setError(e instanceof Error?e.message:'오류가 발생했습니다.')}}
 async function enter(code:string,name:string){
  if(mode==='teacher'){
   if(code){const token=prompt('방 생성 시 받은 교사 운영 키를 입력하세요.');if(!token)return;const a={code,teacherToken:token};setAuth(a);await run({action:'getTeacher',sessionCode:code,teacherToken:token});return;}
   const d=await run({action:'create'});if(d){const a={code:d.sessionCode,teacherToken:d.teacherToken};setAuth(a);setData(await api({action:'getTeacher',sessionCode:a.code,teacherToken:a.teacherToken}));}return;
  }
  const d=await run({action:'join',code,name});if(d){const a={code:d.roomCode,playerToken:d.playerToken};setAuth(a);setData(await api({action:'get',...a}));}
 }
 const leave=()=>{sessionStorage.removeItem('solar-journey-auth');setData(null);setAuth({});setMode('home')};
 if(data?.kind==='student')return <Student data={data} auth={auth} run={run} leave={leave}/>;
 if(data?.kind==='teacher')return <Teacher data={data} auth={auth} run={run} leave={leave}/>;
 return <main className="landing reference-home"><section className="hero reference-hero">{mode==='home'?<div className="reference-actions"><p>6명의 비밀 역할 · 6번의 협상 · 2개의 에너지 경로</p><div className="entry-grid"><button className="entry-card primary" onClick={()=>setMode('student')}><span>학생</span><strong>게임 참여하기</strong><small>조 코드와 이름으로 입장</small></button><button className="entry-card" onClick={()=>setMode('teacher')}><span>교사</span><strong>수업 운영하기</strong><small>5개 조 생성 · 라운드 진행</small></button></div></div>:<Entry mode={mode} error={error} back={()=>{setMode('home');setError('')}} submit={enter}/>}</section></main>
}

function Entry({mode,error,back,submit}:{mode:string,error:string;back:()=>void;submit:(c:string,n:string)=>void}){const [code,setCode]=useState('');const [name,setName]=useState('');return <div className="panel entry-form"><button className="text-btn" onClick={back}>← 처음으로</button><h2>{mode==='teacher'?'교사 운영실':'조에 참여하기'}</h2>{mode==='teacher'?<><p className="muted">새 수업을 만들면 5개 조 코드가 자동 생성됩니다.</p><button className="big-btn" onClick={()=>submit('','')}>새 수업 만들기</button><div className="divider">또는 기존 수업 열기</div><input value={code} onChange={e=>setCode(e.target.value)} placeholder="수업 코드 4자리"/><button className="outline-btn" onClick={()=>submit(code,'')}>기존 수업 열기</button></>:<><label>조 코드<input value={code} onChange={e=>setCode(e.target.value)} placeholder="예: 1234-1"/></label><label>이름<input value={name} onChange={e=>setName(e.target.value)} placeholder="실명 또는 번호+이름" maxLength={12}/></label><button className="big-btn" onClick={()=>submit(code,name)} disabled={!code||!name}>입장하기</button></>}{error&&<p className="error">{error}</p>}</div>}

function Shell({children,title,leave}:{children:React.ReactNode;title:string;leave:()=>void}){return <main className="app"><header><div><span className="logo-dot"/> <strong>태양의 여행</strong></div><span>{title}</span><button className="text-btn" onClick={leave}>나가기</button></header>{children}</main>}
function Student({data,auth,run,leave}:{data:AnyData;auth:AnyData;run:(b:AnyData)=>Promise<any>;leave:()=>void}){const r=data.room,m=r.me;const [energy,setEnergy]=useState('');const [to,setTo]=useState('');const [guessRole,setGuessRole]=useState('');return <Shell title={`${r.group}조 · ${r.code}`} leave={leave}><div className="student-wrap"><section className="phase-card"><div><p className="eyebrow">ROUND {r.round||'—'} · {r.set} SET</p><h2>{phaseName[r.phase]}</h2><p>{phaseHelp[r.phase]}</p></div><Timer deadline={r.deadline}/></section>
 {m.role&&<section className="role-card"><span>나의 비밀 역할</span><h1>{m.role}</h1><p>{m.roleInfo?.rule}</p><div className="goal">개인 목표 · {m.roleInfo?.goal} <b>+3</b></div></section>}
 <section className="path-card"><div className="section-head"><h3>공동 경로</h3><b>{r.paths.length} / 2</b></div><div className="path-track">{[0,1].map(i=><div key={i} className={r.paths[i]?'done':''}><span>{r.paths[i]?'✓':'○'}</span>{r.paths[i]||'미완성 경로'}</div>)}</div><p className={r.round>=5?'final-note':''}>{r.round>=5?'FINAL PHASE · 신규 태양에너지 공급 없음':'2종 이상 완성하면 공동 목표 성공'}</p></section>
 {r.phase==='secret'&&<section className="action-grid"><div className="panel"><div className="section-head"><h3>① 에너지 전환</h3><em>{m.converted?'완료':'최대 1회'}</em></div><select value={energy} onChange={e=>setEnergy(e.target.value)}><option value="">보유 에너지 선택</option>{m.inventory.map((e:any)=><option key={e.id} value={e.id}>{e.type} · {e.path}</option>)}</select><button className="big-btn" disabled={m.converted||!energy} onClick={()=>run({action:'convert',code:auth.code,playerToken:auth.playerToken,energyId:energy})}>전환하기</button></div><div className="panel"><div className="section-head"><h3>② 익명 전달</h3><em>{m.transferred?'완료':'최대 1회'}</em></div><select value={energy} onChange={e=>setEnergy(e.target.value)}><option value="">보낼 에너지 선택</option>{m.inventory.map((e:any)=><option key={e.id} value={e.id}>{e.type} · {e.path}</option>)}</select><select value={to} onChange={e=>setTo(e.target.value)}><option value="">받을 플레이어</option>{r.players.filter((p:any)=>p.id!==m.id).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="big-btn" disabled={m.transferred||!energy||!to} onClick={()=>run({action:'transfer',code:auth.code,playerToken:auth.playerToken,energyId:energy,toId:to})}>익명으로 전달</button></div></section>}
 {r.phase==='guess'&&<section className="panel"><h3>FINAL GUESS</h3><p className="muted">플레이어 한 명과 그 역할을 선택하세요. 제출 후 수정할 수 있습니다.</p><select value={to} onChange={e=>setTo(e.target.value)}><option value="">플레이어 선택</option>{r.players.filter((p:any)=>p.id!==m.id).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={guessRole} onChange={e=>setGuessRole(e.target.value)}><option value="">역할 선택</option>{r.roleChoices.map((x:string)=><option key={x}>{x}</option>)}</select><button className="big-btn" disabled={!to||!guessRole||m.guess} onClick={()=>run({action:'guess',code:auth.code,playerToken:auth.playerToken,toId:to,role:guessRole})}>{m.guess?'추리 제출 완료':'추리 제출'}</button></section>}
 {r.phase==='finished'&&<ScoreTable scores={r.scores}/>}<section className="two-col"><div className="panel"><h3>보유 에너지</h3>{m.inventory.length?m.inventory.map((e:any)=><div className="energy" key={e.id}><b>{e.type}</b><small>{e.path}</small></div>):<p className="empty">아직 보유한 에너지가 없습니다.</p>}</div><div className="panel"><h3>최근 알림</h3>{m.inbox.length?m.inbox.map((x:string,i:number)=><p className="notice" key={i}>{x}</p>):<p className="empty">새 알림이 없습니다.</p>}</div></section></div></Shell>}

function Teacher({data,auth,run,leave}:{data:AnyData;auth:AnyData;run:(b:AnyData)=>Promise<any>;leave:()=>void}){const s=data.session;return <Shell title={`교사 운영실 · ${s.code}`} leave={leave}><div className="teacher-wrap"><section className="teacher-hero"><div><p className="eyebrow">CLASS SESSION</p><h1>수업 코드 {s.code}</h1><p>학생에게 조 코드를 안내하세요. 각 조는 정확히 6명일 때 시작할 수 있습니다.</p><small className="teacher-key">운영 키: {auth.teacherToken}</small></div><button className="big-btn compact" onClick={()=>run({action:'advance',sessionCode:s.code,code:s.rooms[0].code,teacherToken:auth.teacherToken,scope:'all'})}>전체 조 다음 단계</button></section><div className="room-grid">{s.rooms.map((r:any)=><article className="room-card" key={r.code}><div className="section-head"><div><span>{r.group}조 · 역할 세트 {r.set}</span><h2>{r.code}</h2></div><Timer deadline={r.deadline}/></div><div className="room-status"><b>{phaseName[r.phase]}</b><span>{r.round?`${r.round} / 6 라운드`:'시작 전'}</span></div><div className="seats">{Array.from({length:6},(_,i)=><span className={r.players[i]?'filled':''} key={i}>{r.players[i]?.name||`${i+1}번 자리`}</span>)}</div><div className="mini-path">경로 {r.paths.length}/2 {r.paths.join(' · ')}</div>{r.scores?<ScoreTable scores={r.scores}/>:<button className="outline-btn" disabled={r.phase==='lobby'&&r.players.length!==6||r.phase==='finished'} onClick={()=>run({action:'advance',sessionCode:s.code,code:r.code,teacherToken:auth.teacherToken})}>{r.phase==='lobby'?'게임 시작':r.phase==='guess'?'점수 계산':'다음 단계 →'}</button>}</article>)}</div></div></Shell>}
function ScoreTable({scores}:{scores:any[]}){return <section className="panel score"><h3>최종 점수</h3>{scores.map((x:any)=><div className="score-row" key={x.id}><span><b>{x.name}</b><small>{x.role}</small></span><span>{x.common?'공동 ✓':'공동 -2'} · {x.personal?'개인 +3':'개인 0'} · {x.guessCorrect?'추리 +1':'추리 0'} · {x.revealed?'노출 -1':'노출 0'}</span><strong>{x.score}점</strong></div>)}</section>}
