'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
type AnyData=Record<string,any>;
const phaseName:Record<string,string>={lobby:'대기실',negotiation:'협상',secret:'비밀 행동',result:'결과 확인',guess:'최종 추리',finished:'게임 종료'};
const phaseHelp:Record<string,string>={lobby:'7~9명이 들어오면 교사가 시작합니다.',negotiation:'앱 조작 없이 말로 협상하세요.',secret:'전환은 즉시 처리되고, 전달은 단계 종료 후 한꺼번에 도착합니다.',result:'도착한 에너지와 완성된 경로를 확인하세요.',guess:'다른 플레이어 한 명의 역할을 추리하세요.',finished:'역할과 최종 점수가 공개되었습니다.'};
async function api(body:AnyData):Promise<any>{const r=await fetch('/api/game',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d}
function Timer({deadline}:{deadline:number|null}){const[now,setNow]=useState(Date.now());useEffect(()=>{const i=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(i)},[]);if(!deadline)return null;const s=Math.max(0,Math.ceil((deadline-now)/1000));return <span className="timer">{String(Math.floor(s/60)).padStart(2,'0')}:{String(s%60).padStart(2,'0')}</span>}

export default function Home(){
 const[mode,setMode]=useState<'home'|'student'|'teacher'>('home'),[data,setData]=useState<AnyData|null>(null),[auth,setAuth]=useState<AnyData>({}),[error,setError]=useState('');
 useEffect(()=>{try{const saved=localStorage.getItem('solar-journey-auth');if(saved){const a=JSON.parse(saved);setAuth(a);setMode(a.teacherToken?'teacher':'student')}}catch{}},[]);
 useEffect(()=>{if(auth.code)localStorage.setItem('solar-journey-auth',JSON.stringify(auth))},[auth]);
 const refresh=useCallback(async()=>{if(!auth.code)return;try{setData(await api(auth.teacherToken?{action:'getTeacher',sessionCode:auth.code,teacherToken:auth.teacherToken}:{action:'get',code:auth.code,playerToken:auth.playerToken}))}catch(e){setError(e instanceof Error?e.message:'재접속하지 못했습니다.')}},[auth]);
 useEffect(()=>{if(!auth.code)return;refresh();const i=setInterval(refresh,2500);return()=>clearInterval(i)},[auth,refresh]);
 async function run(body:AnyData){setError('');try{const d=await api(body);setData(d.kind?d:null);return d}catch(e){setError(e instanceof Error?e.message:'오류가 발생했습니다.')}}
 async function enter(code:string,name:string){if(mode==='teacher'){if(code){const token=prompt('교사 운영 키를 입력하세요.');if(!token)return;const a={code,teacherToken:token};setAuth(a);await run({action:'getTeacher',sessionCode:code,teacherToken:token});return}const d=await run({action:'create'});if(d){const a={code:d.sessionCode,teacherToken:d.teacherToken};setAuth(a);setData(await api({action:'getTeacher',sessionCode:a.code,teacherToken:a.teacherToken}))}return}const d=await run({action:'join',code,name});if(d){const a={code:d.roomCode,playerToken:d.playerToken};setAuth(a);setData(await api({action:'get',...a}))}}
 const leave=()=>{localStorage.removeItem('solar-journey-auth');setData(null);setAuth({});setMode('home')};
 if(data?.kind==='student')return <Student data={data} auth={auth} run={run} leave={leave}/>;
 if(data?.kind==='teacher')return <Teacher data={data} auth={auth} run={run} leave={leave}/>;
 return <main className="landing reference-home"><section className="hero reference-hero">{auth.code?<div className="panel reconnect"><h2>진행 중인 게임에 다시 연결하는 중…</h2><p>{error||'잠시만 기다려 주세요.'}</p><button className="text-btn" onClick={leave}>다른 게임 참여</button></div>:mode==='home'?<div className="reference-actions"><p>7~9명의 비밀 역할 · 8번의 협상 · 2개의 에너지 경로</p><div className="entry-grid"><button className="entry-card primary" onClick={()=>setMode('student')}><span>학생</span><strong>게임 참여하기</strong><small>조 코드와 이름으로 입장</small></button><button className="entry-card" onClick={()=>setMode('teacher')}><span>교사</span><strong>수업 운영하기</strong><small>5개 조 생성 · 라운드 진행</small></button></div></div>:<Entry mode={mode} error={error} back={()=>{setMode('home');setError('')}} submit={enter}/>}</section></main>
}
function Entry({mode,error,back,submit}:{mode:string;error:string;back:()=>void;submit:(c:string,n:string)=>void}){const[code,setCode]=useState(''),[name,setName]=useState('');return <div className="panel entry-form"><button className="text-btn" onClick={back}>← 처음으로</button><h2>{mode==='teacher'?'교사 운영실':'조에 참여하기'}</h2>{mode==='teacher'?<><p className="muted">새 수업을 만들면 5개 조 코드가 생성됩니다.</p><button className="big-btn" onClick={()=>submit('','')}>새 수업 만들기</button><div className="divider">또는 기존 수업 열기</div><input value={code} onChange={e=>setCode(e.target.value)} placeholder="수업 코드 4자리"/><button className="outline-btn" onClick={()=>submit(code,'')}>기존 수업 열기</button></>:<><label>조 코드<input value={code} onChange={e=>setCode(e.target.value)} placeholder="예: 1234-1"/></label><label>이름<input value={name} onChange={e=>setName(e.target.value)} placeholder="번호+이름" maxLength={12}/></label><button className="big-btn" onClick={()=>submit(code,name)} disabled={!code||!name}>입장하기</button></>}{error&&<p className="error">{error}</p>}</div>}
function Shell({children,title,leave}:{children:React.ReactNode;title:string;leave:()=>void}){return <main className="app"><header><div><span className="logo-dot"/> <strong>태양의 여행</strong></div><span>{title}</span><button className="text-btn" onClick={leave}>나가기</button></header>{children}</main>}
function PhaseTransition({round,phase}:{round:number;phase:string}){const prev=useRef(''),[show,setShow]=useState(false);useEffect(()=>{const key=`${round}-${phase}`;if(prev.current&&prev.current!==key){setShow(true);navigator.vibrate?.(150);const t=setTimeout(()=>setShow(false),2300);prev.current=key;return()=>clearTimeout(t)}prev.current=key},[round,phase]);return show?<div className={`phase-overlay phase-${phase}`}><small>{phase==='finished'?'FINAL':`ROUND ${round}`}</small><strong>{phaseName[phase]}</strong><p>{phaseHelp[phase]}</p></div>:null}
function energyMeta(e:any){if(e.type==='태양E')return{icon:'☀',label:'태양E 조각',cls:'solar'};if(e.type==='화학E'&&e.path.split('→').includes('화석연료'))return{icon:'◉',label:'화석연료 화학E',cls:'fossil'};if(e.type==='화학E')return{icon:'❧',label:'식물 화학E',cls:'plant'};if(e.type==='전기E')return{icon:'ϟ',label:'전기E',cls:'electric'};if(e.type==='운동E')return{icon:'↻',label:'운동E',cls:'motion'};return{icon:'⇧',label:'위치E',cls:'position'}}
function EnergyToken({e,selected,onClick}:{e:any;selected?:boolean;onClick?:()=>void}){const m=energyMeta(e);return <button type="button" className={`energy-token ${m.cls} ${selected?'selected':''}`} onClick={onClick}><span>{m.icon}</span><b>{m.label}</b><small>{e.path.replaceAll('→',' › ')}</small></button>}

function Student({data,auth,run,leave}:{data:AnyData;auth:AnyData;run:(b:AnyData)=>Promise<any>;leave:()=>void}){
 const r=data.room,m=r.me;const[convertIds,setConvertIds]=useState<string[]>([]),[sendId,setSendId]=useState(''),[to,setTo]=useState(''),[guessRole,setGuessRole]=useState('');const needsTwo=['식물','대기·바람','물순환','태양광발전소'].includes(m.role);const needed=needsTwo?2:1;
 const toggle=(id:string)=>setConvertIds(x=>x.includes(id)?x.filter(v=>v!==id):x.length<needed?[...x,id]:x);
 const myScore=r.scores?.find((x:any)=>x.id===m.id);
 return <Shell title={`${r.group}조 · ${r.code}`} leave={leave}><PhaseTransition round={r.round} phase={r.phase}/><div className="student-wrap"><section className="phase-card"><div><p className="eyebrow">ROUND {r.round||'—'} / 8 · {r.set} SET</p><h2>{phaseName[r.phase]}</h2><p>{phaseHelp[r.phase]}</p></div><Timer deadline={r.deadline}/></section>
 {m.role&&<section className="role-card"><span>나의 비밀 역할</span><h1>{m.role}</h1><p>{m.roleInfo?.rule}</p><div className="goal">개인 목표 · {m.roleInfo?.goal}<b>+3</b></div></section>}
 <section className="path-card"><div className="section-head"><h3>공동 경로</h3><b>{r.paths.length} / 2</b></div><div className="path-track">{[0,1].map(i=><div key={i} className={r.paths[i]?'done':''}><span>{r.paths[i]?'✓':'○'}</span>{r.paths[i]||'미완성 경로'}</div>)}</div><p className={r.round>=7?'final-note':''}>{r.round>=7?'FINAL PHASE · 태양E 신규 공급 없음':'서로 다른 경로 2종 이상을 완성하세요'}</p></section>
 {r.phase==='secret'&&<section className="action-grid"><div className="panel action-panel"><div className="section-head"><h3>① 즉시 전환</h3><em>{m.converted?'전환 완료':`${needed}개 선택`}</em></div><div className="token-grid">{m.inventory.map((e:any)=><EnergyToken key={e.id} e={e} selected={convertIds.includes(e.id)} onClick={()=>toggle(e.id)}/>)}</div><button className="big-btn" disabled={m.converted||convertIds.length!==needed} onClick={async()=>{await run({action:'convert',code:auth.code,playerToken:auth.playerToken,energyIds:convertIds});setConvertIds([])}}>선택한 에너지 전환</button></div><div className="panel action-panel"><div className="section-head"><h3>② 익명 전달</h3><em>{m.transferred?'제출 완료':'단계 종료 후 도착'}</em></div><div className="token-grid">{m.inventory.map((e:any)=><EnergyToken key={e.id} e={e} selected={sendId===e.id} onClick={()=>setSendId(e.id)}/>)}</div><select value={to} onChange={e=>setTo(e.target.value)}><option value="">받을 대상 선택</option><option value="CAR">🚗 공동 자동차</option>{r.players.filter((p:any)=>p.id!==m.id).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="big-btn" disabled={m.transferred||!sendId||!to} onClick={()=>run({action:'transfer',code:auth.code,playerToken:auth.playerToken,energyId:sendId,toId:to})}>익명 전달 제출</button></div></section>}
 {r.phase==='guess'&&<section className="panel guess-panel"><h3>FINAL GUESS</h3><p className="muted">다른 플레이어 한 명과 역할을 선택하세요.</p><select value={to} onChange={e=>setTo(e.target.value)}><option value="">플레이어 선택</option>{r.players.filter((p:any)=>p.id!==m.id).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={guessRole} onChange={e=>setGuessRole(e.target.value)}><option value="">역할 선택</option>{r.roleChoices.map((x:string)=><option key={x}>{x}</option>)}</select><button className="big-btn" disabled={!to||!guessRole||m.guess} onClick={()=>run({action:'guess',code:auth.code,playerToken:auth.playerToken,toId:to,role:guessRole})}>{m.guess?'추리 제출 완료':'추리 제출'}</button></section>}
 {r.phase==='finished'&&<><section className="panel named-me"><h3>나를 지목한 사람</h3>{myScore?.guessedBy?.length?myScore.guessedBy.map((g:any,i:number)=><p key={i}><b>{g.name}</b> → {g.role} <span className={g.correct?'correct':'wrong'}>{g.correct?'정답':'오답'}</span></p>):<p className="empty">아무도 나를 지목하지 않았습니다.</p>}</section><ScoreTable scores={r.scores}/></>}
 <section className="two-col"><div className="panel"><h3>보유 에너지</h3><div className="token-grid">{m.inventory.length?m.inventory.map((e:any)=><EnergyToken key={e.id} e={e}/>):<p className="empty">보유한 에너지가 없습니다.</p>}</div></div><div className="panel"><h3>최근 알림</h3>{m.inbox.length?m.inbox.map((x:string,i:number)=><p className="notice" key={i}>{x}</p>):<p className="empty">새 알림이 없습니다.</p>}</div></section></div></Shell>
}
function Teacher({data,auth,run,leave}:{data:AnyData;auth:AnyData;run:(b:AnyData)=>Promise<any>;leave:()=>void}){const s=data.session;return <Shell title={`교사 운영실 · ${s.code}`} leave={leave}><div className="teacher-wrap"><section className="teacher-hero"><div><p className="eyebrow">CLASS SESSION</p><h1>수업 코드 {s.code}</h1><p>각 조는 7~9명으로 시작할 수 있습니다.</p><small className="teacher-key">운영 키: {auth.teacherToken}</small></div><button className="big-btn compact" onClick={()=>run({action:'advance',sessionCode:s.code,code:s.rooms[0].code,teacherToken:auth.teacherToken,scope:'all'})}>전체 조 다음 단계</button></section><div className="room-grid">{s.rooms.map((r:any)=><article className="room-card" key={r.code}><div className="section-head"><div><span>{r.group}조 · 역할 세트 {r.set}</span><h2>{r.code}</h2></div><Timer deadline={r.deadline}/></div><div className="room-status"><b>{phaseName[r.phase]}</b><span>{r.round?`${r.round} / 8 라운드`:`${r.players.length}명 참여`}</span></div><div className="seats">{Array.from({length:9},(_,i)=><span className={r.players[i]?'filled':''} key={i}>{r.players[i]?.name||`${i+1}번 자리`}</span>)}</div><div className="mini-path">경로 {r.paths.length}/2 {r.paths.join(' · ')}</div>{r.scores?<ScoreTable scores={r.scores}/>:<button className="outline-btn" disabled={r.phase==='lobby'&&r.players.length<7||r.phase==='finished'} onClick={()=>run({action:'advance',sessionCode:s.code,code:r.code,teacherToken:auth.teacherToken})}>{r.phase==='lobby'?`${r.players.length}명으로 게임 시작`:r.phase==='guess'?'점수 계산':'다음 단계 →'}</button>}</article>)}</div></div></Shell>}
function ScoreTable({scores}:{scores:any[]}){return <section className="panel score"><h3>최종 점수</h3>{scores.map((x:any)=><div className="score-row" key={x.id}><span><b>{x.name}</b><small>{x.role}</small></span><span>{x.common?'공동 ✓':'공동 -2'} · {x.personal?'개인 +3':'개인 0'} · {x.guessCorrect?'추리 +1':'추리 0'} · {x.revealed?'노출 -1':'노출 0'}<small className="guessers">지목: {x.guessedBy?.map((g:any)=>`${g.name}(${g.role})`).join(', ')||'없음'}</small></span><strong>{x.score}점</strong></div>)}</section>}
