'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from'react';
type AnyData=Record<string,any>;
const phaseName:Record<string,string>={lobby:'대기실',negotiation:'협상',secret:'비밀 행동',result:'결과 확인',guess:'최종 추리',finished:'게임 종료'};
const phaseHelp:Record<string,string>={lobby:'8~10명이 들어오면 교사가 시작합니다.',negotiation:'앱 조작 없이 말로 협상하세요.',secret:'전환은 즉시, 전달은 종료 후 일괄 처리됩니다.',result:'이번 라운드의 전달 결과를 확인하세요.',guess:'다른 플레이어 한 명의 역할을 추리하세요.',finished:'역할과 최종 점수가 공개되었습니다.'};
const pathNames=['태양광 경로','화석연료 경로','화력 경로','풍력 경로','수력 경로'];
async function api(body:AnyData):Promise<any>{const r=await fetch('/api/game',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),d:any=await r.json();if(!r.ok)throw Error(d.error);return d}
function Timer({deadline}:{deadline:number|null}){const[now,setNow]=useState(Date.now());useEffect(()=>{const i=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(i)},[]);if(!deadline)return null;const s=Math.max(0,Math.ceil((deadline-now)/1000));return <span className="timer">{String(Math.floor(s/60)).padStart(2,'0')}:{String(s%60).padStart(2,'0')}</span>}

export default function Home(){
 const[mode,setMode]=useState<'home'|'student'|'teacher'>('home'),[data,setData]=useState<AnyData|null>(null),[auth,setAuth]=useState<AnyData>({}),[error,setError]=useState('');
 useEffect(()=>{try{const saved=localStorage.getItem('solar-journey-auth');if(saved){const a=JSON.parse(saved);setAuth(a);setMode(a.teacherToken?'teacher':'student')}}catch{}},[]);
 useEffect(()=>{if(auth.code)localStorage.setItem('solar-journey-auth',JSON.stringify(auth))},[auth]);
 const refresh=useCallback(async()=>{if(!auth.code)return;try{setData(await api(auth.teacherToken?{action:'getTeacher',sessionCode:auth.code,teacherToken:auth.teacherToken}:{action:'get',code:auth.code,playerToken:auth.playerToken}));setError('')}catch(e){setError(e instanceof Error?e.message:'재접속하지 못했습니다.')}},[auth]);
 useEffect(()=>{if(!auth.code)return;refresh();const i=setInterval(refresh,1800);return()=>clearInterval(i)},[auth,refresh]);
 async function run(body:AnyData){setError('');try{const d=await api(body);setData(d.kind?d:null);return d}catch(e){setError(e instanceof Error?e.message:'오류가 발생했습니다.')}}
 async function enter(code:string,name:string){if(mode==='teacher'){if(code){const token=prompt('교사 운영 키를 입력하세요.');if(!token)return;const a={code,teacherToken:token};setAuth(a);setData(await api({action:'getTeacher',sessionCode:code,teacherToken:token}));return}const d=await run({action:'create'});if(d){const a={code:d.sessionCode,teacherToken:d.teacherToken};setAuth(a);setData(await api({action:'getTeacher',sessionCode:a.code,teacherToken:a.teacherToken}))}return}const d=await run({action:'join',code,name});if(d){const a={code:d.roomCode,playerToken:d.playerToken};setAuth(a);setData(await api({action:'get',...a}))}}
 const leave=()=>{localStorage.removeItem('solar-journey-auth');setData(null);setAuth({});setMode('home')};
 if(data?.kind==='student')return <Student data={data} auth={auth} run={run} leave={leave}/>;
 if(data?.kind==='teacher')return <Teacher data={data} auth={auth} run={run} leave={leave}/>;
 return <main className="landing reference-home"><section className="hero reference-hero">{auth.code?<div className="panel reconnect"><h2>진행 중인 게임에 다시 연결하는 중…</h2><p>{error||'잠시만 기다려 주세요.'}</p><button className="text-btn" onClick={leave}>다른 게임 참여</button></div>:mode==='home'?<div className="reference-actions"><p>8~10명의 비밀 역할 · 8번의 협상 · 2개의 에너지 경로</p><div className="entry-grid"><button className="entry-card primary" onClick={()=>setMode('student')}><span>학생</span><strong>게임 참여하기</strong><small>조 코드와 이름으로 입장</small></button><button className="entry-card" onClick={()=>setMode('teacher')}><span>교사</span><strong>수업 운영하기</strong><small>최대 4개 조 생성 · 라운드 진행</small></button></div></div>:<Entry mode={mode} error={error} back={()=>{setMode('home');setError('')}} submit={enter}/>}</section></main>
}
function Entry({mode,error,back,submit}:{mode:string;error:string;back:()=>void;submit:(c:string,n:string)=>void}){const[code,setCode]=useState(''),[name,setName]=useState('');return <div className="panel entry-form"><button className="text-btn" onClick={back}>← 처음으로</button><h2>{mode==='teacher'?'교사 운영실':'조에 참여하기'}</h2>{mode==='teacher'?<><p className="muted">새 수업을 만들면 4개 조 코드가 생성됩니다. 이 기기에서는 새로고침 후에도 자동으로 다시 연결됩니다.</p><button className="big-btn" onClick={()=>submit('','')}>새 수업 만들기</button></>:<><p className="muted rejoin-help">재접속할 때 같은 조 코드와 이름을 입력하면 기존 역할과 에너지로 돌아갑니다. 이름은 <b>번호+이름</b>으로 입력하세요.</p><label>조 코드<input value={code} onChange={e=>setCode(e.target.value)} placeholder="예: 1234-1"/></label><label>이름<input value={name} onChange={e=>setName(e.target.value)} placeholder="예: 12김태양" maxLength={12}/></label><button className="big-btn" onClick={()=>submit(code,name)} disabled={!code||!name}>입장 또는 재접속</button></>}{error&&<p className="error">{error}</p>}</div>}
function Shell({children,title,leave}:{children:React.ReactNode;title:string;leave:()=>void}){return <main className="app"><header><div><span className="logo-dot"/> <strong>태양의 여행</strong></div><span>{title}</span><button className="text-btn" onClick={leave}>나가기</button></header>{children}</main>}
function PhaseTransition({round,phase}:{round:number;phase:string}){const prev=useRef(''),[show,setShow]=useState(false);useEffect(()=>{const key=round+'-'+phase;if(prev.current&&prev.current!==key){setShow(true);navigator.vibrate?.(150);const t=setTimeout(()=>setShow(false),2300);prev.current=key;return()=>clearTimeout(t)}prev.current=key},[round,phase]);return show?<div className={'phase-overlay phase-'+phase}><small>{phase==='finished'?'FINAL':'ROUND '+round}</small><strong>{phaseName[phase]}</strong><p>{phaseHelp[phase]}</p></div>:null}

const tokenMeta:Record<string,{label:string;cls:string}>={solar:{label:'태양E 조각',cls:'solar'},plantChem:{label:'식물 화학E',cls:'plant'},fossilChem:{label:'화석연료 화학E',cls:'fossil'},electric:{label:'전기E',cls:'electric'},motion:{label:'운동E',cls:'motion'},position:{label:'위치E',cls:'position'}};
const roleSprite:Record<string,string>={'식물':'role-plant','화석연료':'role-fossil','태양광발전소':'role-solar','대기·바람':'role-air','풍력발전소':'role-wind','물순환':'role-water','수력발전소':'role-hydro','화력발전소':'role-thermal'};
function grouped(items:any[]){return Object.values(items.reduce((a:Record<string,any>,e:any)=>{const x=a[e.key]||={key:e.key,count:0,own:0,initial:0};x.count++;if(e.own)x.own++;if(e.initial)x.initial++;a[e.key]=x;return a},{}))}
function EnergyToken({item,selected,onClick}:{item:any;selected?:boolean;onClick?:()=>void}){const m=tokenMeta[item.key];return <button type="button" className={'energy-token '+m.cls+(selected?' selected':'')} onClick={onClick} disabled={!onClick}><span/><b>{m.label} ×{item.count}</b><small>{item.key==='electric'?'직접 생산 '+item.own+' · 받은 에너지 '+(item.count-item.own):item.initial?'초기 저장분 '+item.initial:'보유 수량 '+item.count}</small></button>}
function Inventory({items}:{items:any[]}){const groups=grouped(items);return <section className="panel inventory"><h3>내 에너지</h3><div className="token-grid">{groups.length?groups.map((x:any)=><EnergyToken key={x.key} item={x}/>):<p className="empty">보유한 에너지가 없습니다.</p>}</div></section>}
function GoalLeds({count}:{count:number}){return <section className="path-card led-card"><div className="section-head"><h3>공동 목표</h3><b>{Math.min(2,count)} / 2</b></div><div className="goal-leds">{[0,1].map(i=><span key={i} className={'goal-led '+(count>i?'on':'')}/>)}</div><p>서로 다른 에너지 경로를 달성할 때마다 불이 켜집니다.</p></section>}

function Student({data,auth,run,leave}:{data:AnyData;auth:AnyData;run:(b:AnyData)=>Promise<any>;leave:()=>void}){
 const r=data.room,m=r.me,[sendKey,setSendKey]=useState(''),[to,setTo]=useState(''),[guessRole,setGuessRole]=useState(''),[solarPopup,setSolarPopup]=useState(false),groups=useMemo(()=>grouped(m.inventory),[m.inventory]),selected:any=groups.find((x:any)=>x.key===sendKey),myScore=r.scores?.find((x:any)=>x.id===m.id),showGame=['negotiation','secret','result'].includes(r.phase),canCar=selected&&(sendKey==='electric'||sendKey==='fossilChem')&&!(sendKey==='fossilChem'&&selected.initial===selected.count),solarCount=m.inventory.filter((e:any)=>e.key==='solar').length,previousSolar=useRef<number|null>(null);
 useEffect(()=>{if(previousSolar.current!==null&&solarCount>previousSolar.current){setSolarPopup(true);const t=setTimeout(()=>setSolarPopup(false),2600);previousSolar.current=solarCount;return()=>clearTimeout(t)}previousSolar.current=solarCount},[solarCount]);
 return <Shell title={r.group+'조 · '+r.code} leave={leave}><PhaseTransition round={r.round} phase={r.phase}/>{solarPopup&&<div className="solar-toast"><span className="solar-token-art"/><strong>태양 에너지 조각을 획득하였습니다!</strong></div>}<div className="student-wrap"><section className={'phase-card phase-'+r.phase}><div><p className="eyebrow">ROUND {r.round||'—'} / 8</p><h2>{phaseName[r.phase]}</h2><p>{phaseHelp[r.phase]}</p></div><Timer deadline={r.deadline}/></section>
 {m.role&&<section className={'role-card '+(roleSprite[m.role]||'')}><div className="role-copy"><span>나의 비밀 역할</span><h1>{m.role}</h1><p>{m.roleInfo?.rule}</p><div className="goal">개인 목표 · {m.roleInfo?.goal}<b>{m.convertedCount||0}회</b></div></div><span className="role-art" aria-hidden="true"/></section>}
 {showGame&&<Inventory items={m.inventory}/>} {showGame&&<GoalLeds count={r.commonCount}/>} {r.round>=7&&showGame&&<p className="final-note standalone">FINAL PHASE · 태양E 신규 공급 없음</p>}
 {r.phase==='negotiation'&&<section className="panel instruction"><h3>지금 할 일</h3><p>앱은 조작하지 않고, 누가 어떤 에너지를 필요로 하는지 말로 협상하세요.</p></section>}
 {r.phase==='secret'&&<section className="action-grid"><div className="panel action-panel"><div className="section-head"><h3>① 즉시 전환</h3><em>{m.converted?'전환 완료':'라운드당 1회'}</em></div><p className="muted">{m.roleInfo?.rule}</p><button className="big-btn" disabled={m.converted||!m.canConvert} onClick={()=>run({action:'convert',code:auth.code,playerToken:auth.playerToken})}>{m.canConvert?'에너지 즉시 전환':'필요한 에너지 부족'}</button></div><div className="panel action-panel"><div className="section-head"><h3>② 익명 전달</h3><em>{m.transferred?'제출 완료':'종료 후 일괄 도착'}</em></div><div className="token-grid">{groups.map((x:any)=><EnergyToken key={x.key} item={x} selected={sendKey===x.key} onClick={()=>setSendKey(x.key)}/>)}</div><select value={to} onChange={e=>setTo(e.target.value)}><option value="">받을 대상 선택</option>{canCar&&<option value="CAR">🚗 공동 자동차</option>}{r.players.filter((p:any)=>p.id!==m.id).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="big-btn" disabled={m.transferred||!sendKey||!to} onClick={()=>run({action:'transfer',code:auth.code,playerToken:auth.playerToken,energyKey:sendKey,toId:to})}>익명 전달 제출</button></div></section>}
 {r.phase==='result'&&<section className="panel"><h3>이번 라운드 알림</h3>{m.inbox.length?m.inbox.map((x:string,i:number)=><p className="notice" key={i}>{x}</p>):<p className="empty">새 알림이 없습니다.</p>}</section>}
 {r.phase==='guess'&&<section className="panel guess-panel"><h3>FINAL GUESS</h3><p className="muted">다른 플레이어 한 명과 역할을 선택하세요.</p><select value={to} onChange={e=>setTo(e.target.value)}><option value="">플레이어 선택</option>{r.players.filter((p:any)=>p.id!==m.id).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={guessRole} onChange={e=>setGuessRole(e.target.value)}><option value="">역할 선택</option>{r.roleChoices.map((x:string)=><option key={x}>{x}</option>)}</select><button className="big-btn" disabled={!to||!guessRole||m.guess} onClick={()=>run({action:'guess',code:auth.code,playerToken:auth.playerToken,toId:to,role:guessRole})}>{m.guess?'추리 제출 완료':'추리 제출'}</button></section>}
 {r.phase==='finished'&&<><FinalPaths status={r.pathStatus}/><section className="panel named-me"><h3>나를 지목한 사람</h3>{myScore?.guessedBy?.length?myScore.guessedBy.map((g:any,i:number)=><p key={i}><b>{g.name}</b> → {g.role} <span className={g.correct?'correct':'wrong'}>{g.correct?'정답':'오답'}</span></p>):<p className="empty">아무도 나를 지목하지 않았습니다.</p>}</section><ScoreTable scores={r.scores}/></>}
 </div></Shell>
}
function FinalPaths({status}:{status:any}){return <section className="path-card final-paths"><h3>최종 완성 경로</h3>{pathNames.map(k=>{const x=status?.[k]||{count:0,need:k==='태양광 경로'?2:1,complete:false};return <div key={k} className={x.complete?'done':''}><span>{k}</span><b>{x.complete?'완성':Math.min(x.count,x.need)+' / '+x.need}</b></div>})}</section>}
function useTeacherSound(rooms:any[]){const[enabled,setEnabled]=useState(true),ctx=useRef<AudioContext|null>(null),last=useRef('');const prime=()=>{if(!ctx.current)ctx.current=new AudioContext();ctx.current.resume()};useEffect(()=>{const i=setInterval(()=>{if(!enabled||!ctx.current)return;const active=rooms.filter(r=>r.deadline).map(r=>Math.max(0,Math.ceil((r.deadline-Date.now())/1000))).filter(s=>s>=1&&s<=5);if(!active.length)return;const s=Math.min(...active),key=s+'-'+rooms.map(r=>r.deadline).join('-');if(last.current===key)return;last.current=key;const c=ctx.current,o=c.createOscillator(),g=c.createGain();o.frequency.value=s===1?880:660;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.16);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.17)},150);return()=>clearInterval(i)},[rooms,enabled]);return{enabled,setEnabled,prime}}
function Teacher({data,auth,run,leave}:{data:AnyData;auth:AnyData;run:(b:AnyData)=>Promise<any>;leave:()=>void}){const s=data.session,sound=useTeacherSound(s.rooms),act=(b:AnyData)=>{sound.prime();return run(b)},changeTime=(delta:number)=>act({action:'setNegotiation',sessionCode:s.code,teacherToken:auth.teacherToken,seconds:s.negotiationSeconds+delta});return <Shell title={'교사 운영실 · '+s.code} leave={leave}><div className="teacher-wrap"><section className="teacher-hero"><div><p className="eyebrow">CLASS SESSION</p><h1>수업 코드 {s.code}</h1><p>최대 4개 조 · 조당 8~10명</p></div><div className="teacher-controls"><div className="time-setting"><span>협상 기본 시간</span><button onClick={()=>changeTime(-30)} disabled={s.negotiationSeconds<=60}>−30초</button><b>{Math.floor(s.negotiationSeconds/60)}:{String(s.negotiationSeconds%60).padStart(2,'0')}</b><button onClick={()=>changeTime(30)} disabled={s.negotiationSeconds>=300}>+30초</button></div><button className="sound-toggle" onClick={()=>{sound.prime();sound.setEnabled(!sound.enabled)}}>{sound.enabled?'🔊 카운트다운음 켜짐':'🔇 카운트다운음 꺼짐'}</button><button className="big-btn compact" onClick={()=>act({action:'advance',sessionCode:s.code,code:s.rooms[0].code,teacherToken:auth.teacherToken,scope:'all'})}>전체 조 다음 단계</button></div></section><div className="room-grid">{s.rooms.map((r:any)=>{const submitted=r.players.filter((p:any)=>p.submitted).length;return <article className="room-card" key={r.code}><div className="section-head"><div><span>{r.group}조</span><h2>{r.code}</h2></div><Timer deadline={r.deadline}/></div><div className="room-status"><b>{phaseName[r.phase]}</b><span>{r.round?r.round+' / 8 라운드':r.players.length+'명 참여'}</span></div><div className="seats">{Array.from({length:10},(_,i)=><span className={r.players[i]?'filled':''} key={i}>{r.players[i]?.name||(i+1)+'번 자리'}</span>)}</div>{r.phase==='secret'&&<div className="submission">전달 제출 {submitted} / {r.players.length}</div>}<div className="teacher-paths">{pathNames.map(k=>{const x=r.pathStatus[k];return <span className={x.complete?'ok':''} key={k}>{k.replace(' 경로','')} {x.complete?'✓':x.count?x.count+'/'+x.need:'—'}</span>})}</div>{r.phase==='negotiation'&&<button className="outline-btn small" onClick={()=>act({action:'extend',sessionCode:s.code,code:r.code,teacherToken:auth.teacherToken})}>협상 +30초 연장</button>}{r.scores?<ScoreTable scores={r.scores}/>:<button className="outline-btn" disabled={r.phase==='lobby'&&r.players.length<8||r.phase==='finished'} onClick={()=>act({action:'advance',sessionCode:s.code,code:r.code,teacherToken:auth.teacherToken})}>{r.phase==='lobby'?r.players.length+'명으로 게임 시작':r.phase==='guess'?'점수 계산':'다음 단계 →'}</button>}</article>})}</div></div></Shell>}
function ScoreTable({scores}:{scores:any[]}){return <section className="panel score"><h3>최종 점수</h3>{scores.map((x:any)=><div className="score-row" key={x.id}><span><b>{x.name}</b><small>{x.role}</small></span><span>{x.common?'공동 ✓':'공동 -2'} · {x.personal?'개인 +3':'개인 0'} · {x.guessCorrect?'추리 +1':'추리 0'} · {x.revealed?'노출 -1':'노출 0'}<small className="guessers">지목: {x.guessedBy?.map((g:any)=>g.name+'('+g.role+')').join(', ')||'없음'}</small></span><strong>{x.score}점</strong></div>)}</section>}
