import {advance,ALL_ROLES,canConvert,convertEnergy,energyKey,energyLabel,join,newSession,normalizeSession,ROLE_INFO,scores,transfer,type Room,type Session} from'@/lib/game';
export const runtime='nodejs';
type SessionRow={state:Session;updated_at:number};
function supabase(){const url=process.env.SUPABASE_URL?.replace(/\/$/,'');const key=process.env.SUPABASE_SECRET_KEY;if(!url||!key)throw Error('서버 데이터베이스 연결이 설정되지 않았습니다.');return{url,key,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'}}}
async function query(path:string,init:RequestInit={}){const{url,headers}=supabase();const response=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{...headers,...init.headers},cache:'no-store'});if(!response.ok){const detail=await response.text();throw Error(`데이터베이스 요청 실패 (${response.status}): ${detail.slice(0,160)}`)}return response}
async function load(code:string){const sessionCode=code.split('-')[0];const response=await query(`sessions?code=eq.${encodeURIComponent(sessionCode)}&select=state,updated_at&limit=1`);const rows=await response.json()as SessionRow[];if(!rows[0])throw Error('방을 찾을 수 없습니다.');return{session:normalizeSession(rows[0].state),version:rows[0].updated_at}}
async function exists(code:string){const response=await query(`sessions?code=eq.${encodeURIComponent(code)}&select=code&limit=1`);return((await response.json())as unknown[]).length>0}
async function insert(s:Session){await query('sessions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({code:s.code,teacher_token:s.teacherToken,state:s,updated_at:1})})}
async function mutate<T>(code:string,fn:(s:Session)=>T){for(let attempt=0;attempt<50;attempt++){if(attempt)await new Promise(resolve=>setTimeout(resolve,2+Math.floor(Math.random()*Math.min(20,attempt+3))));const{session,version}=await load(code);const value=fn(session);const response=await query(`sessions?code=eq.${encodeURIComponent(session.code)}&updated_at=eq.${version}&select=updated_at`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({teacher_token:session.teacherToken,state:session,updated_at:version+1})});const rows=await response.json()as {updated_at:number}[];if(rows.length)return{session,value}}throw Error('동시에 제출된 행동을 저장하지 못했습니다. 다시 눌러 주세요.')}
const roomOf=(s:Session,code:string)=>{const r=s.rooms.find(x=>x.code===code);if(!r)throw Error('조 코드를 확인해 주세요.');return r};
const publicPathStatus=(r:Room)=>Object.fromEntries(['태양광 경로','화석연료 경로','화력 경로','풍력 경로','수력 경로'].map(k=>[k,{count:r.pathProgress[k]||0,need:k==='태양광 경로'?2:1,complete:r.paths.includes(k)}]));
function studentView(r:Room,token:string){const me=r.players.find(p=>p.token===token);if(!me)throw Error('참여 정보를 찾을 수 없습니다.');return{kind:'student',room:{code:r.code,group:r.group,phase:r.phase,round:r.round,deadline:r.deadline,commonCount:Math.min(2,r.paths.length),paths:r.phase==='finished'?r.paths:[],pathStatus:r.phase==='finished'?publicPathStatus(r):undefined,players:r.players.map(p=>({id:p.id,name:p.name,ready:!!p.role})),me:{id:me.id,name:me.name,role:me.role,roleInfo:me.role?ROLE_INFO[me.role]:null,inventory:me.inventory.map(e=>({id:e.id,key:energyKey(e),label:energyLabel(e),own:e.createdBy===me.id,initial:!!e.initial})),converted:me.converted,canConvert:canConvert(me),transferred:me.transferred,inbox:me.inbox.slice(0,6),guess:me.guess,convertedCount:me.stats.converted},scores:r.phase==='finished'?scores(r):null,roleChoices:ALL_ROLES}}}
function teacherView(s:Session){return{kind:'teacher',session:{code:s.code,negotiationSeconds:s.negotiationSeconds,rooms:s.rooms.map(r=>({code:r.code,group:r.group,phase:r.phase,round:r.round,deadline:r.deadline,commonCount:Math.min(2,r.paths.length),pathStatus:publicPathStatus(r),players:r.players.map(p=>({id:p.id,name:p.name,role:r.phase==='finished'?p.role:undefined,submitted:r.phase==='secret'?p.transferred:undefined})),scores:r.phase==='finished'?scores(r):null}))}}}
export async function POST(req:Request){try{const b=await req.json()as Record<string,any>;
 if(b.action==='create'){let s=newSession();while(await exists(s.code))s=newSession();await insert(s);return Response.json({sessionCode:s.code,teacherToken:s.teacherToken,rooms:s.rooms.map(r=>r.code)})}
 if(b.action==='getTeacher'){const{session}=await load(b.sessionCode);if(b.teacherToken!==session.teacherToken)throw Error('교사 운영 키가 올바르지 않습니다.');return Response.json(teacherView(session))}
 if(b.action==='get'){const{session}=await load(b.code);return Response.json(studentView(roomOf(session,b.code),b.playerToken))}
 if(b.action==='join'){const out=await mutate(b.code,s=>join(roomOf(s,b.code),String(b.name||'').trim().slice(0,12)));return Response.json({playerToken:out.value.token,roomCode:b.code})}
 if(b.action==='advance'){const out=await mutate(b.sessionCode||b.code,s=>{if(b.teacherToken!==s.teacherToken)throw Error('교사 운영 키가 올바르지 않습니다.');if(b.scope==='all')s.rooms.forEach(r=>{try{advance(r,s.negotiationSeconds)}catch{}});else advance(roomOf(s,b.code),s.negotiationSeconds)});return Response.json(teacherView(out.session))}
 if(b.action==='setNegotiation'){const out=await mutate(b.sessionCode,s=>{if(b.teacherToken!==s.teacherToken)throw Error('교사 운영 키가 올바르지 않습니다.');s.negotiationSeconds=Math.min(300,Math.max(60,Math.round(Number(b.seconds)/30)*30))});return Response.json(teacherView(out.session))}
 if(b.action==='extend'){const out=await mutate(b.sessionCode,s=>{if(b.teacherToken!==s.teacherToken)throw Error('교사 운영 키가 올바르지 않습니다.');const r=roomOf(s,b.code);if(r.phase!=='negotiation'||!r.deadline)throw Error('협상 단계에서만 연장할 수 있습니다.');r.deadline+=30000});return Response.json(teacherView(out.session))}
 const out=await mutate(b.code,s=>{const r=roomOf(s,b.code),p=r.players.find(x=>x.token===b.playerToken);if(!p)throw Error('참여 정보를 찾을 수 없습니다.');if(b.action==='convert')convertEnergy(r,p);else if(b.action==='transfer')transfer(r,p,b.toId,b.energyKey);else if(b.action==='guess'){if(r.phase!=='guess')throw Error('지금은 역할을 추리할 수 없습니다.');if(b.toId===p.id)throw Error('다른 플레이어를 선택하세요.');p.guess=`${b.toId}|${b.role}`}else throw Error('알 수 없는 요청입니다.');return p.token});
 return Response.json(studentView(roomOf(out.session,b.code),out.value));
 }catch(e){return Response.json({error:e instanceof Error?e.message:'요청을 처리하지 못했습니다.'},{status:400})}}
