import {env} from'cloudflare:workers';
import {advance,convertEnergy,join,newSession,ROLE_INFO,ROLE_SETS,scores,transfer,type Room,type Session} from'@/lib/game';
export const runtime='edge';
async function init(){await env.DB.prepare('CREATE TABLE IF NOT EXISTS sessions (code TEXT PRIMARY KEY, teacher_token TEXT NOT NULL, state TEXT NOT NULL, updated_at INTEGER NOT NULL)').run()}
async function load(code:string){await init();const row=await env.DB.prepare('SELECT state,updated_at FROM sessions WHERE code=?').bind(code.split('-')[0]).first<{state:string;updated_at:number}>();if(!row)throw Error('방을 찾을 수 없습니다.');return{session:JSON.parse(row.state)as Session,version:row.updated_at}}
async function insert(s:Session){await env.DB.prepare('INSERT INTO sessions(code,teacher_token,state,updated_at) VALUES(?,?,?,?)').bind(s.code,s.teacherToken,JSON.stringify(s),1).run()}
async function mutate<T>(code:string,fn:(s:Session)=>T){for(let attempt=0;attempt<10;attempt++){const{session,version}=await load(code);const value=fn(session);const result=await env.DB.prepare('UPDATE sessions SET teacher_token=?,state=?,updated_at=? WHERE code=? AND updated_at=?').bind(session.teacherToken,JSON.stringify(session),version+1,session.code,version).run();if((result.meta?.changes||0)>0)return{session,value}}throw Error('동시에 제출된 행동을 저장하지 못했습니다. 다시 눌러 주세요.')}
const roomOf=(s:Session,code:string)=>{const r=s.rooms.find(x=>x.code===code);if(!r)throw Error('조 코드를 확인해 주세요.');return r};
function studentView(r:Room,token:string){const me=r.players.find(p=>p.token===token);if(!me)throw Error('참여 정보를 찾을 수 없습니다.');return{kind:'student',room:{code:r.code,group:r.group,set:r.set,phase:r.phase,round:r.round,deadline:r.deadline,paths:r.paths,log:r.log.slice(0,4),players:r.players.map(p=>({id:p.id,name:p.name,ready:!!p.role})),me:{id:me.id,name:me.name,role:me.role,roleInfo:me.role?ROLE_INFO[me.role]:null,inventory:me.inventory,converted:me.converted,transferred:me.transferred,inbox:me.inbox.slice(0,6),guess:me.guess},scores:r.phase==='finished'?scores(r):null,roleChoices:ROLE_SETS[r.set]}}}
function teacherView(s:Session){return{kind:'teacher',session:{code:s.code,rooms:s.rooms.map(r=>({code:r.code,group:r.group,set:r.set,phase:r.phase,round:r.round,deadline:r.deadline,paths:r.paths,players:r.players.map(p=>({id:p.id,name:p.name,role:r.phase==='finished'?p.role:undefined})),log:r.log.slice(0,4),scores:r.phase==='finished'?scores(r):null}))}}}
export async function POST(req:Request){try{const b=await req.json()as Record<string,any>;
 if(b.action==='create'){await init();let s=newSession();while(await env.DB.prepare('SELECT code FROM sessions WHERE code=?').bind(s.code).first())s=newSession();await insert(s);return Response.json({sessionCode:s.code,teacherToken:s.teacherToken,rooms:s.rooms.map(r=>r.code)})}
 if(b.action==='getTeacher'){const{session}=await load(b.sessionCode);if(b.teacherToken!==session.teacherToken)throw Error('교사 운영 키가 올바르지 않습니다.');return Response.json(teacherView(session))}
 if(b.action==='get'){const{session}=await load(b.code);return Response.json(studentView(roomOf(session,b.code),b.playerToken))}
 if(b.action==='join'){const out=await mutate(b.code,s=>join(roomOf(s,b.code),String(b.name||'').trim().slice(0,12)));return Response.json({playerToken:out.value.token,roomCode:b.code})}
 if(b.action==='advance'){const out=await mutate(b.sessionCode||b.code,s=>{if(b.teacherToken!==s.teacherToken)throw Error('교사 운영 키가 올바르지 않습니다.');if(b.scope==='all')s.rooms.forEach(r=>{try{advance(r)}catch{}});else advance(roomOf(s,b.code))});return Response.json(teacherView(out.session))}
 const out=await mutate(b.code,s=>{const r=roomOf(s,b.code),p=r.players.find(x=>x.token===b.playerToken);if(!p)throw Error('참여 정보를 찾을 수 없습니다.');if(b.action==='convert')convertEnergy(r,p,b.energyIds||[]);else if(b.action==='transfer')transfer(r,p,b.toId,b.energyId);else if(b.action==='guess'){if(r.phase!=='guess')throw Error('지금은 역할을 추리할 수 없습니다.');if(b.toId===p.id)throw Error('다른 플레이어를 선택하세요.');p.guess=`${b.toId}|${b.role}`}else throw Error('알 수 없는 요청입니다.');return p.token});
 return Response.json(studentView(roomOf(out.session,b.code),out.value));
 }catch(e){return Response.json({error:e instanceof Error?e.message:'요청을 처리하지 못했습니다.'},{status:400})}}
