import { env } from 'cloudflare:workers';
import { advance, convertEnergy, join, newSession, ROLE_INFO, ROLE_SETS, scores, transfer, type Room, type Session } from '@/lib/game';

export const runtime='edge';
async function init(){await env.DB.prepare('CREATE TABLE IF NOT EXISTS sessions (code TEXT PRIMARY KEY, teacher_token TEXT NOT NULL, state TEXT NOT NULL, updated_at INTEGER NOT NULL)').run();}
async function load(code:string){await init();const row=await env.DB.prepare('SELECT state FROM sessions WHERE code=?').bind(code.split('-')[0]).first<{state:string}>();if(!row)throw Error('방을 찾을 수 없습니다.');return JSON.parse(row.state) as Session;}
async function save(s:Session){await env.DB.prepare('INSERT INTO sessions(code,teacher_token,state,updated_at) VALUES(?,?,?,?) ON CONFLICT(code) DO UPDATE SET state=excluded.state,updated_at=excluded.updated_at').bind(s.code,s.teacherToken,JSON.stringify(s),Date.now()).run();}
const roomOf=(s:Session,code:string)=>{const r=s.rooms.find(x=>x.code===code);if(!r)throw Error('조 코드를 확인해 주세요.');return r};
function studentView(r:Room,token:string){const me=r.players.find(p=>p.token===token);if(!me)throw Error('참여 정보를 찾을 수 없습니다.');return{kind:'student',room:{code:r.code,group:r.group,set:r.set,phase:r.phase,round:r.round,deadline:r.deadline,paths:r.paths,log:r.log.slice(0,4),players:r.players.map(p=>({id:p.id,name:p.name,ready:!!p.role})),me:{id:me.id,name:me.name,role:me.role,roleInfo:me.role?ROLE_INFO[me.role]:null,inventory:me.inventory,converted:me.converted,transferred:me.transferred,inbox:me.inbox.slice(0,5),guess:me.guess},scores:r.phase==='finished'?scores(r):null,roleChoices:ROLE_SETS[r.set]}};}
function teacherView(s:Session){return{kind:'teacher',session:{code:s.code,rooms:s.rooms.map(r=>({code:r.code,group:r.group,set:r.set,phase:r.phase,round:r.round,deadline:r.deadline,paths:r.paths,players:r.players.map(p=>({id:p.id,name:p.name,role:r.phase==='finished'?p.role:undefined})),log:r.log.slice(0,4),scores:r.phase==='finished'?scores(r):null}))}};}
export async function POST(req:Request){try{const b=await req.json() as Record<string,string>;if(b.action==='create'){await init();let s=newSession();while(await env.DB.prepare('SELECT code FROM sessions WHERE code=?').bind(s.code).first())s=newSession();await save(s);return Response.json({sessionCode:s.code,teacherToken:s.teacherToken,rooms:s.rooms.map(r=>r.code)});}
  const s=await load(b.code||b.sessionCode);if(b.action==='join'){const r=roomOf(s,b.code);const p=join(r,b.name.trim().slice(0,12));await save(s);return Response.json({playerToken:p.token,roomCode:r.code});}
  if(b.action==='getTeacher'){if(b.teacherToken!==s.teacherToken)throw Error('교사 운영 키가 올바르지 않습니다.');return Response.json(teacherView(s));}
  const r=roomOf(s,b.code);if(b.action==='get')return Response.json(studentView(r,b.playerToken));
  if(b.action==='advance'){if(b.teacherToken!==s.teacherToken)throw Error('교사 운영 키가 올바르지 않습니다.');if(b.scope==='all')s.rooms.forEach(x=>{try{advance(x)}catch{}});else advance(r);await save(s);return Response.json(teacherView(s));}
  const p=r.players.find(x=>x.token===b.playerToken);if(!p)throw Error('참여 정보를 찾을 수 없습니다.');
  if(b.action==='convert')convertEnergy(r,p,b.energyId);else if(b.action==='transfer')transfer(r,p,b.toId,b.energyId);else if(b.action==='guess'){if(r.phase!=='guess')throw Error('지금은 역할을 추리할 수 없습니다.');if(b.toId===p.id)throw Error('다른 플레이어를 선택하세요.');p.guess=`${b.toId}|${b.role}`;}else throw Error('알 수 없는 요청입니다.');await save(s);return Response.json(studentView(r,p.token));
}catch(e){return Response.json({error:e instanceof Error?e.message:'요청을 처리하지 못했습니다.'},{status:400});}}
